## Admin Configuration File for Azure Machine Learning Service

## Configurations for the Azure Machine Learning Workspace creation
workspace:
  ## Subscription: Your Azure Subscription
  subscription: 8b41ca9c-0c5a-4c01-b49b-5bb8d329cc27
  ## Department: 4 characters
  department: bgmr
  ## Team: 10 characters
  team: bluegranit
  ## Region: (such as `westus2` or `westeurope`)
  region: eastus2
  ## Region Abbreviation: 2 characters (such as such as `w2` or `we`)
  region_abbv: e2
  ## Environment: 3 characters (e.g. `res`, `dev`, or `pro`)
  environment: dev
  ## Admin Microsoft account (`user@domain.com`)
  admin: cford@blue-granite.com
  ## Security Group: optional
  security_group:
  ## ADLS: `y` to create the data lake store or `n` to skip
  create_dls: n

## Configurations for the Compute Target creation
compute:
  ## Workpace: Get AMLS workspace name from previous workspace creation step
  workspace: bgmrbluegranite2devws
  ## Nodes: Maximum number of nodes in the cluster
  nodes: 1
  ## Priority: either `lowpriority` or `dedicated`
  priority: lowpriority
  ## VM SKU: VM SKU from `az vm list-sizes --location <region> --output table`
  vm_sku: STANDARD_DS3_V2
